### ISSUE TITLE
permission denied in home directory in Docker container

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-tutorial#55]
During the tutorial on June 23rd 2020 we ran into permission problems when trying to create files in the Docker container, because we used a directory that was created outside of the container as home directory in the container.

The problem was eventually easily fixed with the `chmod 1777` command that was added in https://github.com/easybuilders/easybuild-tutorial/commit/c24696f8807f7634cc4aabf0d3e9f3c142d096d3 by @ocaisa.

@ChristianKniep @akesandgren Any more details on this, and suggestions for a proper long-term fix?

Should we just `chmod a+w` the directory after creating it, or is there a better way to ensure this always works?

Another problem with mounting a directory in the container is that the pre-downloaded sources that are pre-fetched into `easybuild/sources` in the home directory in the container image are no longer available (which could have prevented some of the SourceForge download trouble we hit).

**Comment by akesandgren** [comment]
Don't mount a directory from outside. At least not when the container runs as a specific user inside. Doing chmod a+w is bad form, always.

The sources should be pre-fetched into /easybuild/sources since that is irrelevant of $HOME coming from outside or not.
Then force set the env for sources to point there.

The problem is really only the HMNS module rebuild part. Is there a way to make eb not write the logs and stuff into the software tree??

**Comment by boegel** [comment]
@akesandgren Yeah, the latter bit is actually a bug in EasyBuild, it shouldn't require write permissions in `.../software` when doing stuff with `--module-only`. May not be trivial to fix though...

My main motivation for mounting a directory in the container is that people still have the files they created after the exit the container image. Otherwise it's all gone as soon as their back in the initial shell session...
